name: roshan syncerr
#
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Roshan Syncerr

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          wget -qO- https://api.github.com/repos/donwa/gclone/releases/latest \
          | grep browser_download_url | grep Linux_x86_64 | cut -d '"' -f 4 \
          | wget --no-verbose -i- -O- | gzip -d -c > rclone
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
      - name: Config
        run: |
          mkdir -p ~/.config/rclone
          mkdir -p sa
          cd sa
          curl -L "${{ secrets.GCLONE_DLURL }}" -o accounts.zip
          unzip -jq -o accounts.zip
          rm ._0.json
          rm accounts.zip
          cd ..
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.GCLONE_CONFIG_SYNC }}
          EOF
      - name: gclone Run
        run: |
          echo "::add-mask::gclone sa file: /home/runner/.config/rclone/sa/"
          echo "::add-mask::.json"
          rclone copy roshan:/ roshanbackup:/ --drive-server-side-across-configs --stats=1s --stats-one-line -P --checkers=320 --transfers=320 --drive-pacer-min-sleep=1ms --drive-pacer-burst=4000
